"use client";

import { FormEvent, useEffect, useState } from "react";
import Protected from "@/components/Protected";
import { api, Profile } from "@/lib/api";

const avatars: Record<string, string> = { ember: "◒", lumen: "✦", tide: "≈", moss: "❋", dusk: "◐" };

export default function Profiles() {
  const [profiles, setProfiles] = useState<Profile[]>([]); const [error, setError] = useState(""); const load = () => api<Profile[]>("/profiles").then(setProfiles); useEffect(() => { load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); try { await api("/profiles", { method: "POST", body: JSON.stringify({ name: form.get("name"), avatar: form.get("avatar"), maturity_limit: Number(form.get("maturity")) }) }); event.currentTarget.reset(); load(); } catch (reason) { setError((reason as Error).message); } }
  return <Protected><main className="app-main page"><p className="eyebrow">WHO&apos;S WATCHING?</p><h1>Profiles.</h1><p className="muted">Each profile keeps its own viewing boundary.</p><div className="profile-layout"><section className="profile-list">{profiles.map(profile => <article className={profile.active ? "profile active-profile" : "profile"} key={profile.id}><div className={`avatar ${profile.avatar}`}>{avatars[profile.avatar] || "✦"}</div><div><h2>{profile.name}</h2><p>Up to {profile.maturity_limit}+</p></div><div className="profile-actions">{!profile.active && <button className="ghost small" onClick={async () => { await api(`/profiles/${profile.id}/select`, { method: "PUT" }); load(); }}>Select</button>}<button className="text-button" onClick={async () => { const name = prompt("Profile name", profile.name)?.trim(); if (!name) return; await api(`/profiles/${profile.id}`, { method: "PUT", body: JSON.stringify({ name, avatar: profile.avatar, maturity_limit: profile.maturity_limit }) }); load(); }}>Rename</button><button className="text-button" disabled={profiles.length === 1} onClick={async () => { await api(`/profiles/${profile.id}`, { method: "DELETE" }); load(); }}>Delete</button></div></article>)}</section><form className="panel" onSubmit={create}><p className="eyebrow">NEW PROFILE</p><h2>Add someone.</h2><label>Name<input name="name" maxLength={24} required /></label><label>Avatar<select name="avatar">{Object.keys(avatars).map(name => <option key={name}>{name}</option>)}</select></label><label>Maturity limit<select name="maturity" defaultValue="18"><option value="7">7+</option><option value="13">13+</option><option value="16">16+</option><option value="18">18+</option></select></label>{error && <p className="error" role="alert">{error}</p>}<button className="button">Create profile</button></form></div></main></Protected>;
}
